/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-31 04:36:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<title>반려동물종합관리플랫폼</title>\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link href=\"../resources/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("<link href=\"../resources/assets/img/apple-touch-icon.png\"\r\n");
      out.write("	rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Fonts -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com\" rel=\"preconnect\">\r\n");
      out.write("<link href=\"https://fonts.gstatic.com\" rel=\"preconnect\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS Files -->\r\n");
      out.write("<link href=\"../resources/assets/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../resources/assets/vendor/bootstrap-icons/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../resources/assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../resources/assets/vendor/glightbox/css/glightbox.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../resources/assets/vendor/swiper/swiper-bundle.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main CSS File -->\r\n");
      out.write("<link href=\"../resources/assets/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- =======================================================\r\n");
      out.write("  * Template Name: Impact\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/impact-bootstrap-business-website-template/\r\n");
      out.write("  * Updated: Jun 29 2024 with Bootstrap v5.3.3\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!-- 공통 css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/common.css\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<style>\r\n");
      out.write("@font-face {\r\n");
      out.write("    font-family: 'RixInooAriDuriR';\r\n");
      out.write("    src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_2207-01@1.0/RixInooAriDuriR.woff2') format('woff2');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("@font-face {\r\n");
      out.write("	font-family: 'Noto Sans KR';\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	src: url(//fonts.gstatic.com/ea/notosanskr/v2/NotoSansKR-Medium.woff2)\r\n");
      out.write("		format('woff2'),\r\n");
      out.write("		url(//fonts.gstatic.com/ea/notosanskr/v2/NotoSansKR-Medium.woff)\r\n");
      out.write("		format('woff'),\r\n");
      out.write("		url(//fonts.gstatic.com/ea/notosanskr/v2/NotoSansKR-Medium.otf)\r\n");
      out.write("		format('opentype');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	/* font-family: 'RixInooAriDuriR'; */\r\n");
      out.write("	font-family: 'Noto Sans KR', sans-serif !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	font-family: 'Noto Sans KR', sans-serif !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-box {\r\n");
      out.write("	border-radius: 20px !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  부트스트랩 스타일 수정  -->\r\n");
      out.write("<style>\r\n");
      out.write(".accent-background {\r\n");
      out.write("	background-color: white !important;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".accent-background p {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topbar {\r\n");
      out.write("	background-color: #FADA5A !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".branding, .branding a, .branding h1 {\r\n");
      out.write("	background-color: gray !important;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-box {\r\n");
      out.write("	background-color: #FADA5A !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("	background-color: gray !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <body class=\"index-page\">\r\n");
      out.write("	<header id=\"header\" class=\"header fixed-top\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"topbar d-flex align-items-center\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"container d-flex justify-content-center justify-content-md-between\">\r\n");
      out.write("				<div class=\"contact-info d-flex align-items-center\">\r\n");
      out.write("					<i class=\"bi bi-envelope d-flex align-items-center\"><a\r\n");
      out.write("						href=\"mailto:contact@example.com\">contact@example.com</a></i> <i\r\n");
      out.write("						class=\"bi bi-phone d-flex align-items-center ms-4\"><span>+1\r\n");
      out.write("							5589 55488 55</span></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"social-links d-none d-md-flex align-items-center\">\r\n");
      out.write("					<a href=\"#\" class=\"twitter\"><i class=\"bi bi-twitter-x\"></i></a> <a\r\n");
      out.write("						href=\"#\" class=\"facebook\"><i class=\"bi bi-facebook\"></i></a> <a\r\n");
      out.write("						href=\"#\" class=\"instagram\"><i class=\"bi bi-instagram\"></i></a> <a\r\n");
      out.write("						href=\"#\" class=\"linkedin\"><i class=\"bi bi-linkedin\"></i></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		End Top Bar\r\n");
      out.write("\r\n");
      out.write("		<div class=\"branding d-flex align-items-cente\">\r\n");
      out.write("\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"container position-relative d-flex align-items-center justify-content-between\">\r\n");
      out.write("				<a href=\"index.html\" class=\"logo d-flex align-items-center\"> Uncomment the line below if you also wish to use an image logo\r\n");
      out.write("					<img src=\"resources/assets/img/logo.png\" alt=\"\">\r\n");
      out.write("					<h1 class=\"sitename\">LOGO</h1>\r\n");
      out.write("				</a>\r\n");
      out.write("\r\n");
      out.write("				<nav id=\"navmenu\" class=\"navmenu\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\" class=\"active\">다이어리<br></a></li>\r\n");
      out.write("						<li class=\"dropdown\"><a href=\"blog.html\"><span>커뮤니티</span>\r\n");
      out.write("								<i class=\"bi bi-chevron-down toggle-dropdown\"></i></a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">Dropdown 1</a></li>\r\n");
      out.write("								<li><a href=\"#\">Dropdown 2</a></li>\r\n");
      out.write("								<li><a href=\"#\">Dropdown 3</a></li>\r\n");
      out.write("								<li><a href=\"#\">Dropdown 4</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">플레이스</a></li>\r\n");
      out.write("						<li><a href=\"#portfolio\">뉴스</a></li>\r\n");
      out.write("						<li><a href=\"#team\">쇼핑몰</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><a href=\"#\">문의</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<i class=\"mobile-nav-toggle d-xl-none bi bi-list\"></i>\r\n");
      out.write("				</nav>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</header> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<main class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Hero Section -->\r\n");
      out.write("		<section id=\"hero\" class=\"hero section accent-background\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container position-relative\" data-aos=\"fade-up\"\r\n");
      out.write("				data-aos-delay=\"100\">\r\n");
      out.write("				<div class=\"row gy-5 justify-content-between\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<span>Welcome to </span><span class=\"accent\">(Logo name)</span>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<p>사람과 반려동물이 함께 더불어 행복한 세상을 만들어갑니다.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-5 order-1 order-lg-2\">\r\n");
      out.write("						<img src=\"../resources/assets/img/hero-img.png\" class=\"img-fluid\"\r\n");
      out.write("							alt=\"\" style=\"border-radius: 20px;\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"icon-boxes position-relative\" data-aos=\"fade-up\"\r\n");
      out.write("				data-aos-delay=\"200\">\r\n");
      out.write("				<div class=\"container position-relative\">\r\n");
      out.write("					<div class=\"row gy-4 mt-5\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-xl-3 col-md-6\">\r\n");
      out.write("							<div class=\"icon-box\">\r\n");
      out.write("								<div class=\"icon\">\r\n");
      out.write("									<i class=\"bi bi-easel\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<h4 class=\"title\">\r\n");
      out.write("									<a href=\"\" class=\"stretched-link\">다이어리</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!--End Icon Box -->\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-xl-3 col-md-6\">\r\n");
      out.write("							<div class=\"icon-box\">\r\n");
      out.write("								<div class=\"icon\">\r\n");
      out.write("									<i class=\"bi bi-gem\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<h4 class=\"title\">\r\n");
      out.write("									<a href=\"\" class=\"stretched-link\">커뮤니티</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!--End Icon Box -->\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-xl-3 col-md-6\">\r\n");
      out.write("							<div class=\"icon-box\">\r\n");
      out.write("								<div class=\"icon\">\r\n");
      out.write("									<i class=\"bi bi-geo-alt\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<h4 class=\"title\">\r\n");
      out.write("									<a href=\"\" class=\"stretched-link\">플레이스</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!--End Icon Box -->\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-xl-3 col-md-6\">\r\n");
      out.write("							<div class=\"icon-box\">\r\n");
      out.write("								<div class=\"icon\">\r\n");
      out.write("									<i class=\"bi bi-command\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<h4 class=\"title\">\r\n");
      out.write("									<a href=\"\" class=\"stretched-link\">뉴스</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!--End Icon Box -->\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- /Hero Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Services Section -->\r\n");
      out.write("		<!-- ## 뉴스 -->\r\n");
      out.write("		<section id=\"services\" class=\"services section\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Section Title -->\r\n");
      out.write("			<div class=\"container section-title\" data-aos=\"fade-up\">\r\n");
      out.write("				<h2>반려동물 뉴스</h2>\r\n");
      out.write("				<p>Necessitatibus eius consequatur ex aliquid fuga eum quidem\r\n");
      out.write("					sint consectetur velit</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- End Section Title -->\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row gy-4\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-4 col-md-6\" data-aos=\"fade-up\"\r\n");
      out.write("						data-aos-delay=\"100\">\r\n");
      out.write("						<div class=\"service-item  position-relative\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<i class=\"bi bi-activity\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("							<h3>Nesciunt Mete</h3>\r\n");
      out.write("							<p>Provident nihil minus qui consequatur non omnis maiores.\r\n");
      out.write("								Eos accusantium minus dolores iure perferendis tempore et\r\n");
      out.write("								consequatur.</p>\r\n");
      out.write("							<a href=\"service-details.html\" class=\"readmore stretched-link\">Read\r\n");
      out.write("								more <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Service Item -->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-4 col-md-6\" data-aos=\"fade-up\"\r\n");
      out.write("						data-aos-delay=\"200\">\r\n");
      out.write("						<div class=\"service-item position-relative\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<i class=\"bi bi-broadcast\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("							<h3>Eosle Commodi</h3>\r\n");
      out.write("							<p>Ut autem aut autem non a. Sint sint sit facilis nam iusto\r\n");
      out.write("								sint. Libero corrupti neque eum hic non ut nesciunt dolorem.</p>\r\n");
      out.write("							<a href=\"service-details.html\" class=\"readmore stretched-link\">Read\r\n");
      out.write("								more <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Service Item -->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-4 col-md-6\" data-aos=\"fade-up\"\r\n");
      out.write("						data-aos-delay=\"300\">\r\n");
      out.write("						<div class=\"service-item position-relative\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<i class=\"bi bi-easel\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("							<h3>Ledo Markt</h3>\r\n");
      out.write("							<p>Ut excepturi voluptatem nisi sed. Quidem fuga consequatur.\r\n");
      out.write("								Minus ea aut. Vel qui id voluptas adipisci eos earum corrupti.</p>\r\n");
      out.write("							<a href=\"service-details.html\" class=\"readmore stretched-link\">Read\r\n");
      out.write("								more <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Service Item -->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-4 col-md-6\" data-aos=\"fade-up\"\r\n");
      out.write("						data-aos-delay=\"400\">\r\n");
      out.write("						<div class=\"service-item position-relative\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<i class=\"bi bi-bounding-box-circles\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("							<h3>Asperiores Commodit</h3>\r\n");
      out.write("							<p>Non et temporibus minus omnis sed dolor esse consequatur.\r\n");
      out.write("								Cupiditate sed error ea fuga sit provident adipisci neque.</p>\r\n");
      out.write("							<a href=\"service-details.html\" class=\"readmore stretched-link\">Read\r\n");
      out.write("								more <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Service Item -->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-4 col-md-6\" data-aos=\"fade-up\"\r\n");
      out.write("						data-aos-delay=\"500\">\r\n");
      out.write("						<div class=\"service-item position-relative\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<i class=\"bi bi-calendar4-week\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("							<h3>Velit Doloremque</h3>\r\n");
      out.write("							<p>Cumque et suscipit saepe. Est maiores autem enim facilis\r\n");
      out.write("								ut aut ipsam corporis aut. Sed animi at autem alias eius labore.</p>\r\n");
      out.write("							<a href=\"service-details.html\" class=\"readmore stretched-link\">Read\r\n");
      out.write("								more <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Service Item -->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-4 col-md-6\" data-aos=\"fade-up\"\r\n");
      out.write("						data-aos-delay=\"600\">\r\n");
      out.write("						<div class=\"service-item position-relative\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<i class=\"bi bi-chat-square-text\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("							<h3>Dolori Architecto</h3>\r\n");
      out.write("							<p>Hic molestias ea quibusdam eos. Fugiat enim doloremque aut\r\n");
      out.write("								neque non et debitis iure. Corrupti recusandae ducimus enim.</p>\r\n");
      out.write("							<a href=\"service-details.html\" class=\"readmore stretched-link\">Read\r\n");
      out.write("								more <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Service Item -->\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- /Services Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Recent Posts Section -->\r\n");
      out.write("		<!-- ## 커뮤니티 글 -->\r\n");
      out.write("		<section id=\"recent-posts\" class=\"recent-posts section\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Section Title -->\r\n");
      out.write("			<div class=\"container section-title\" data-aos=\"fade-up\">\r\n");
      out.write("				<h2>커뮤니티 최신글</h2>\r\n");
      out.write("				<p>Necessitatibus eius consequatur ex aliquid fuga eum quidem\r\n");
      out.write("					sint consectetur velit</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- End Section Title -->\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row gy-4\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-xl-4 col-md-6\" data-aos=\"fade-up\"\r\n");
      out.write("						data-aos-delay=\"100\">\r\n");
      out.write("						<article>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"post-img\">\r\n");
      out.write("								<img src=\"../resources/assets/img/blog/blog-1.jpg\" alt=\"\"\r\n");
      out.write("									class=\"img-fluid\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"post-category\">Politics</p>\r\n");
      out.write("\r\n");
      out.write("							<h2 class=\"title\">\r\n");
      out.write("								<a href=\"blog-details.html\">Dolorum optio tempore voluptas\r\n");
      out.write("									dignissimos</a>\r\n");
      out.write("							</h2>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"d-flex align-items-center\">\r\n");
      out.write("								<img src=\"../resources/assets/img/blog/blog-author.jpg\" alt=\"\"\r\n");
      out.write("									class=\"img-fluid post-author-img flex-shrink-0\">\r\n");
      out.write("								<div class=\"post-meta\">\r\n");
      out.write("									<p class=\"post-author\">Maria Doe</p>\r\n");
      out.write("									<p class=\"post-date\">\r\n");
      out.write("										<time datetime=\"2022-01-01\">Jan 1, 2022</time>\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</article>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End post list item -->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-xl-4 col-md-6\" data-aos=\"fade-up\"\r\n");
      out.write("						data-aos-delay=\"200\">\r\n");
      out.write("						<article>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"post-img\">\r\n");
      out.write("								<img src=\"../resources/assets/img/blog/blog-2.jpg\" alt=\"\"\r\n");
      out.write("									class=\"img-fluid\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"post-category\">Sports</p>\r\n");
      out.write("\r\n");
      out.write("							<h2 class=\"title\">\r\n");
      out.write("								<a href=\"blog-details.html\">Nisi magni odit consequatur\r\n");
      out.write("									autem nulla dolorem</a>\r\n");
      out.write("							</h2>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"d-flex align-items-center\">\r\n");
      out.write("								<img src=\"../resources/assets/img/blog/blog-author-2.jpg\" alt=\"\"\r\n");
      out.write("									class=\"img-fluid post-author-img flex-shrink-0\">\r\n");
      out.write("								<div class=\"post-meta\">\r\n");
      out.write("									<p class=\"post-author\">Allisa Mayer</p>\r\n");
      out.write("									<p class=\"post-date\">\r\n");
      out.write("										<time datetime=\"2022-01-01\">Jun 5, 2022</time>\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</article>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End post list item -->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-xl-4 col-md-6\" data-aos=\"fade-up\"\r\n");
      out.write("						data-aos-delay=\"300\">\r\n");
      out.write("						<article>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"post-img\">\r\n");
      out.write("								<img src=\"../resources/assets/img/blog/blog-3.jpg\" alt=\"\"\r\n");
      out.write("									class=\"img-fluid\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"post-category\">Entertainment</p>\r\n");
      out.write("\r\n");
      out.write("							<h2 class=\"title\">\r\n");
      out.write("								<a href=\"blog-details.html\">Possimus soluta ut id suscipit\r\n");
      out.write("									ea ut in quo quia et soluta</a>\r\n");
      out.write("							</h2>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"d-flex align-items-center\">\r\n");
      out.write("								<img src=\"../resources/assets/img/blog/blog-author-3.jpg\" alt=\"\"\r\n");
      out.write("									class=\"img-fluid post-author-img flex-shrink-0\">\r\n");
      out.write("								<div class=\"post-meta\">\r\n");
      out.write("									<p class=\"post-author\">Mark Dower</p>\r\n");
      out.write("									<p class=\"post-date\">\r\n");
      out.write("										<time datetime=\"2022-01-01\">Jun 22, 2022</time>\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</article>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End post list item -->\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- End recent posts list -->\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- /Recent Posts Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<footer id=\"footer\" class=\"footer accent-background\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container footer-top\">\r\n");
      out.write("			<div class=\"row gy-4\">\r\n");
      out.write("				<div class=\"col-lg-5 col-md-12 footer-about\">\r\n");
      out.write("					<a href=\"index.html\" class=\"logo d-flex align-items-center\"> <span\r\n");
      out.write("						class=\"sitename\">Impact</span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<p>Cras fermentum odio eu feugiat lide par naso tierra. Justo\r\n");
      out.write("						eget nada terra videa magna derita valies darta donna mare\r\n");
      out.write("						fermentum iaculis eu non diam phasellus.</p>\r\n");
      out.write("					<div class=\"social-links d-flex mt-4\">\r\n");
      out.write("						<a href=\"\"><i class=\"bi bi-twitter-x\"></i></a> <a href=\"\"><i\r\n");
      out.write("							class=\"bi bi-facebook\"></i></a> <a href=\"\"><i\r\n");
      out.write("							class=\"bi bi-instagram\"></i></a> <a href=\"\"><i\r\n");
      out.write("							class=\"bi bi-linkedin\"></i></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-2 col-6 footer-links\">\r\n");
      out.write("					<h4>Useful Links</h4>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">Home</a></li>\r\n");
      out.write("						<li><a href=\"#\">About us</a></li>\r\n");
      out.write("						<li><a href=\"#\">Services</a></li>\r\n");
      out.write("						<li><a href=\"#\">Terms of service</a></li>\r\n");
      out.write("						<li><a href=\"#\">Privacy policy</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-2 col-6 footer-links\">\r\n");
      out.write("					<h4>Our Services</h4>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">Web Design</a></li>\r\n");
      out.write("						<li><a href=\"#\">Web Development</a></li>\r\n");
      out.write("						<li><a href=\"#\">Product Management</a></li>\r\n");
      out.write("						<li><a href=\"#\">Marketing</a></li>\r\n");
      out.write("						<li><a href=\"#\">Graphic Design</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"col-lg-3 col-md-12 footer-contact text-center text-md-start\">\r\n");
      out.write("					<h4>Contact Us</h4>\r\n");
      out.write("					<p>A108 Adam Street</p>\r\n");
      out.write("					<p>New York, NY 535022</p>\r\n");
      out.write("					<p>United States</p>\r\n");
      out.write("					<p class=\"mt-4\">\r\n");
      out.write("						<strong>Phone:</strong> <span>+1 5589 55488 55</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<strong>Email:</strong> <span>info@example.com</span>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container copyright text-center mt-4\">\r\n");
      out.write("			<p>\r\n");
      out.write("				Â© <span>Copyright</span> <strong class=\"px-1 sitename\">Impact</strong>\r\n");
      out.write("				<span>All Rights Reserved</span>\r\n");
      out.write("			</p>\r\n");
      out.write("			<div class=\"credits\">\r\n");
      out.write("				<!-- All the links in the footer should remain intact. -->\r\n");
      out.write("				<!-- You can delete the links only if you've purchased the pro version. -->\r\n");
      out.write("				<!-- Licensing information: https://bootstrapmade.com/license/ -->\r\n");
      out.write("				<!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->\r\n");
      out.write("				Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<!-- Scroll Top -->\r\n");
      out.write("	<a href=\"#\" id=\"scroll-top\"\r\n");
      out.write("		class=\"scroll-top d-flex align-items-center justify-content-center\"><i\r\n");
      out.write("		class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\r\n");
      out.write("	<!-- Preloader -->\r\n");
      out.write("	<div id=\"preloader\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor JS Files -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"../resources/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"../resources/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("	<script src=\"../resources/assets/vendor/aos/aos.js\"></script>\r\n");
      out.write("	<script src=\"../resources/assets/vendor/glightbox/js/glightbox.min.js\"></script>\r\n");
      out.write("	<script src=\"../resources/assets/vendor/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"../resources/assets/vendor/purecounter/purecounter_vanilla.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"../resources/assets/vendor/imagesloaded/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"../resources/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Main JS File -->\r\n");
      out.write("<script src=\"../resources/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
