/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-31 04:36:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.diary;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class diary_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.89/apache-tomcat-9.0.89/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("file:/C:/apache-tomcat-9.0.89/apache-tomcat-9.0.89/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1714735332000L));
    _jspx_dependants.put("/WEB-INF/views/diary/../top.jsp", Long.valueOf(1722399409783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- fullCalendar API 관련 JS파일 -->\r\n");
      out.write("<script src='../resources/index.global.js'></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/common.css\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("<!-- <script src=\"https://cdn.jsdelivr.net/npm/@fullcalendar/googlecalendar@6.1.8/index.global.min.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function del(table_name, idx){\r\n");
      out.write("		if(confirm(\"정말 삭제하시겠습니까?\") == false) return;\r\n");
      out.write("		location.href = \"diary_delete.do?table_name=\" + table_name + \"&idx=\" + idx;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function formatTime(timeString) {\r\n");
      out.write("	    if (!timeString) return '';\r\n");
      out.write("	    // ' '로 문자열을 나누고 두 번째 부분(시간)을 가져온 후, ':'로 나누어 시간과 분만 추출\r\n");
      out.write("	    return timeString.split(' ')[1].substr(0, 5);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	function generate_html(response) {\r\n");
      out.write("		   \r\n");
      out.write("	    let formHtml = '';\r\n");
      out.write("\r\n");
      out.write("	    // 체중\r\n");
      out.write("	    if (response.weight_list.length > 0) {\r\n");
      out.write("	        formHtml += '체중<br>';\r\n");
      out.write("	        response.weight_list.forEach(function(WeightVo) {\r\n");
      out.write("	            formHtml += '<div><form action=\"diary_modify_form.do\" method=\"post\"><table class=\"table\"><tbody>';\r\n");
      out.write("	            formHtml += '<tr><th>반려동물</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"w_rdate\" value=\"' + (WeightVo.p_idx || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>체중(kg)</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"p_idx\" value=\"' + (WeightVo.w_weight || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '</tbody></table></form></div>';\r\n");
      out.write("	            formHtml += '<a href=\"diary_view.do?table_name=weight&idx=' + (WeightVo.w_idx || '') + '\"><input class=\"diary-btn-yellow\" type=\"button\" value=\"상세보기\" style=\"margin-right:50px;\"></a>';\r\n");
      out.write("	            formHtml += '<input class=\"diary-btn-yellow\" type=\"button\" value=\"삭제\" onclick=\"del(\\'weight\\',' + (WeightVo.w_idx || '') + ');\"><br>';\r\n");
      out.write("	        });\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    // 산책\r\n");
      out.write("	    if (response.stoll_list.length > 0) {\r\n");
      out.write("	        formHtml += '산책<br>';\r\n");
      out.write("	        response.stoll_list.forEach(function(StollVo) {\r\n");
      out.write("	        	\r\n");
      out.write("	        	 let formattedStartTime = formatTime(StollVo.s_stime);\r\n");
      out.write("	             let formattedEndTime = formatTime(StollVo.s_etime);\r\n");
      out.write("	             \r\n");
      out.write("	             formHtml += '<div><form action=\"diary_modify_form.do\" method=\"post\"><table class=\"table\"><tbody>';\r\n");
      out.write("	             formHtml += '<tr><th>반려동물</th>';\r\n");
      out.write("	             formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"p_idx\" value=\"' + (StollVo.p_idx || '') + '\"></td></tr>';\r\n");
      out.write("	             formHtml += '<tr><th>시작시간</th>';\r\n");
      out.write("	             formHtml += '<td><input class=\"form-control form-control-lg\" type=\"time\" name=\"s_stime\" value=\"' + formattedStartTime + '\" readonly /></td></tr>';\r\n");
      out.write("	             formHtml += '<tr><th>종료시간</th>';\r\n");
      out.write("	             formHtml += '<td><input class=\"form-control form-control-lg\" type=\"time\" name=\"s_etime\" value=\"' + formattedEndTime + '\" readonly /></td></tr>';\r\n");
      out.write("	             formHtml += '<tr><th>거리(m)</th>';\r\n");
      out.write("	             formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"s_distance\" value=\"' + (StollVo.s_distance || '') + '\"></td></tr>';\r\n");
      out.write("	             formHtml += '</tbody></table></form></div>';\r\n");
      out.write("	             formHtml += '<a href=\"diary_view.do?table_name=stoll&idx=' + (StollVo.s_idx || '') + '\"><input class=\"diary-btn-yellow\" type=\"button\" value=\"상세보기\" style=\"margin-right:50px;\"></a>';\r\n");
      out.write("	             formHtml += '<input class=\"diary-btn-yellow\" type=\"button\" value=\"삭제\" onclick=\"del(\\'stoll\\',' + (StollVo.s_idx || '') + ');\"><br>';\r\n");
      out.write("	        \r\n");
      out.write("	        	\r\n");
      out.write("	            /* formHtml += '<div><form action=\"diary_modify_form.do\" method=\"post\"><table class=\"table\"><tbody>';\r\n");
      out.write("	            formHtml += '<tr><th>반려동물</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"p_idx\" value=\"' + (StollVo.p_idx || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>시작시간</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"time\" name=\"s_stime\" value=\"' + (StollVo.s_stime || '') + '\"></td></tr>';\r\n");
      out.write("	          \r\n");
      out.write("	            formHtml += '<tr><th>종료시간</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"time\" name=\"s_etime\" value=\"' + (StollVo.s_etime || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>거리(m)</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"s_distance\" value=\"' + (StollVo.s_distance || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '</tbody></table></form></div>';\r\n");
      out.write("	            formHtml += '<a href=\"diary_view.do?table_name=stoll&idx=' + (StollVo.s_idx || '') + '\"><input class=\"diary-btn-yellow\" type=\"button\" value=\"상세보기\" style=\"margin-right:50px;\"></a>';\r\n");
      out.write("	            formHtml += '<input class=\"diary-btn-yellow\" type=\"button\" value=\"삭제\" onclick=\"del(\\'stoll\\',' + (StollVo.s_idx || '') + ');\"><br>';\r\n");
      out.write("	         */});\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    // 사료/간식/영양제\r\n");
      out.write("	    if (response.feeding_list.length > 0) {\r\n");
      out.write("	        formHtml += '사료/간식/영양제<br>';\r\n");
      out.write("	        response.feeding_list.forEach(function(FeedingVo) {\r\n");
      out.write("	        	\r\n");
      out.write("	        	let formattedTime = formatTime(FeedingVo.f_time);\r\n");
      out.write("	             \r\n");
      out.write("	             \r\n");
      out.write("	            formHtml += '<div><form action=\"diary_modify_form.do\" method=\"post\"><table class=\"table\"><tbody>';\r\n");
      out.write("	            formHtml += '<tr><th>반려동물</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"p_idx\" value=\"' + (FeedingVo.p_idx || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>시간</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"time\" name=\"f_time\" value=\"' + formattedTime + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>종류</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"f_type\" value=\"' + (FeedingVo.f_type || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>사료명</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"f_pname\" value=\"' + (FeedingVo.f_pname || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '</tbody></table></form></div>';\r\n");
      out.write("	            formHtml += '<a href=\"diary_view.do?table_name=feeding&idx=' + (FeedingVo.f_idx || '') + '\"><input class=\"diary-btn-yellow\" type=\"button\" value=\"상세보기\" style=\"margin-right:50px;\"></a>';\r\n");
      out.write("	            formHtml += '<input class=\"diary-btn-yellow\" type=\"button\" value=\"삭제\" onclick=\"del(\\'feeding\\',' + (FeedingVo.f_idx || '') + ');\"><br>';\r\n");
      out.write("	        });\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    // 건강\r\n");
      out.write("	    if (response.health_list.length > 0) {\r\n");
      out.write("	        formHtml += '건강<br>';\r\n");
      out.write("	        response.health_list.forEach(function(HealthVo) {\r\n");
      out.write("	        	let formattedTime = formatTime(HealthVo.h_time);\r\n");
      out.write("	        	\r\n");
      out.write("	            formHtml += '<div><form action=\"diary_modify_form.do\" method=\"post\"><table class=\"table\"><tbody>';\r\n");
      out.write("	            formHtml += '<tr><th>반려동물</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"h_p_idx\" value=\"' + (HealthVo.p_idx || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>시간</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"time\" name=\"h_time\" value=\"' + formattedTime + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>종류</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"h_type\" value=\"' + (HealthVo.h_type || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>진단명</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"h_hname\" value=\"' + (HealthVo.h_hname || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '</tbody></table></form></div>';\r\n");
      out.write("	            formHtml += '<a href=\"diary_view.do?table_name=health&idx=' + (HealthVo.h_idx || '') + '\"><input class=\"diary-btn-yellow\" type=\"button\" value=\"상세보기\" style=\"margin-right:50px;\"></a>';\r\n");
      out.write("	            formHtml += '<input class=\"diary-btn-yellow\" type=\"button\" value=\"삭제\" onclick=\"del(\\'health\\',' + (HealthVo.h_idx || '') + ');\"><br>';\r\n");
      out.write("	        });\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    // 메모\r\n");
      out.write("	    if (response.note_list.length > 0) {\r\n");
      out.write("	        formHtml += '메모<br>';\r\n");
      out.write("	        response.note_list.forEach(function(NoteVo) {\r\n");
      out.write("	        	let formattedTime = formatTime(NoteVo.o_time);\r\n");
      out.write("	        	\r\n");
      out.write("	            formHtml += '<table class=\"table\">';\r\n");
      out.write("	            formHtml += '<tbody>';\r\n");
      out.write("	            formHtml += '<tr><th>반려동물</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"p_idx\" value=\"' + (NoteVo.p_idx || '') + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>시간</th>';\r\n");
      out.write("	            formHtml += '<td><input class=\"form-control form-control-lg\" type=\"time\" name=\"o_time\" value=\"' + formattedTime + '\"></td></tr>';\r\n");
      out.write("	            formHtml += '<tr><th>메모</th>';\r\n");
      out.write("	            formHtml += '<td><textarea class=\"form-control form-control-lg\" name=\"o_content\" rows=\"3\" placeholder=\"내용을 입력해주세요.\" oninput=\"this.style.height=\\'\\' , this.style.height= this.scrollHeight + \\'px\\'\">' + (NoteVo.o_content || '') + '</textarea></td></tr>';\r\n");
      out.write("	            formHtml += '</tbody></table>';\r\n");
      out.write("	            formHtml += '<a href=\"diary_view.do?table_name=note&idx=' + (NoteVo.o_idx || '') + '\"><input class=\"diary-btn-yellow\" type=\"button\" value=\"상세보기\" style=\"margin-right:50px;\"></a>';\r\n");
      out.write("	            formHtml += '<input class=\"diary-btn-yellow\" type=\"button\" value=\"삭제\" onclick=\"del(\\'note\\',' + (NoteVo.o_idx || '') + ');\"><br>';\r\n");
      out.write("	        });\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    formHtml += '<br><br>';\r\n");
      out.write("	    return formHtml;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("\r\n");
      out.write("	let calendar = new Calendar(calendarEl, {\r\n");
      out.write("	 plugins: [ interactionPlugin ],\r\n");
      out.write("	 dateClick: function(info) {\r\n");
      out.write("	 alert('Clicked on: ' + info.dateStr);\r\n");
      out.write("	 alert('Coordinates: ' + info.jsEvent.pageX + ',' + info.jsEvent.pageY);\r\n");
      out.write("	 alert('Current view: ' + info.view.type);\r\n");
      out.write("	 // change the day's background color just for fun\r\n");
      out.write("	 info.dayEl.style.backgroundColor = 'red';\r\n");
      out.write("	 }\r\n");
      out.write("	 });*/\r\n");
      out.write("	 \r\n");
      out.write("\r\n");
      out.write("	 $(document).ready(function(){\r\n");
      out.write("	     let json_calendar_all_data;\r\n");
      out.write("	     let today = new Date();   \r\n");
      out.write("\r\n");
      out.write("	     let year = today.getFullYear(); // 년도\r\n");
      out.write("	     let month = ('0' + (today.getMonth() + 1)).slice(-2);\r\n");
      out.write("	     let day = ('0' + today.getDate()).slice(-2);\r\n");
      out.write("\r\n");
      out.write("	     let today_full = (year + '-' + month + '-' + day);\r\n");
      out.write("	     \r\n");
      out.write("	     $.ajax({\r\n");
      out.write("	         url: 'diary_select_date.do',\r\n");
      out.write("	         type: 'GET',\r\n");
      out.write("	         data: { date: today_full },\r\n");
      out.write("	         success: function(response) {\r\n");
      out.write("	             // 체중 데이터를 처리하여 HTML 생성\r\n");
      out.write("	             let test = generate_html(response);\r\n");
      out.write("	             \r\n");
      out.write("	             // HTML을 페이지에 삽입\r\n");
      out.write("	             $('#diary_select_date').html(test);\r\n");
      out.write("	         },\r\n");
      out.write("	         error: function(error) {\r\n");
      out.write("	             console.error('Error fetching data:', error);\r\n");
      out.write("	         }\r\n");
      out.write("	     });\r\n");
      out.write("	     \r\n");
      out.write("	     $.ajax({\r\n");
      out.write("	     	  url: 'full_calendar_json_data.do', // 요청할 URL\r\n");
      out.write("	     	  method: 'GET', // HTTP 메서드 (기본적으로 GET)\r\n");
      out.write("	     	  dataType: 'json', // 응답 데이터 타입\r\n");
      out.write("	     	  success: function(data) {\r\n");
      out.write("	     	    // 요청 성공 시 처리\r\n");
      out.write("	     	    console.log(data);\r\n");
      out.write("\r\n");
      out.write("	     		// FullCalendar 사용 예시\r\n");
      out.write("	            /* $('#calendar').fullCalendar({\r\n");
      out.write("	                events: data.map(function(item) {\r\n");
      out.write("	                    return {\r\n");
      out.write("	                        title: item.title,\r\n");
      out.write("	                        start: item.start\r\n");
      out.write("	                    };\r\n");
      out.write("	                })\r\n");
      out.write("	            }); */\r\n");
      out.write("	     	  }\r\n");
      out.write("	     	});\r\n");
      out.write("	 });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	 // 캘린더 표시 \r\n");
      out.write("	 document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("	   var calendarEl = document.getElementById('calendar');\r\n");
      out.write("\r\n");
      out.write("	   var calendar = new FullCalendar.Calendar(calendarEl, {\r\n");
      out.write("	     headerToolbar: {\r\n");
      out.write("	       left: 'prevYear,prev,next,nextYear today',\r\n");
      out.write("	       center: 'title',\r\n");
      out.write("	       right: 'dayGridMonth,dayGridWeek,dayGridDay'\r\n");
      out.write("	     },\r\n");
      out.write("	     initialDate: '2024-07-26',\r\n");
      out.write("	     dateClick: function(info) { // 날짜 클릭시 이벤트 \r\n");
      out.write("	 	    // alert('Clicked on: ' + info.dateStr);\r\n");
      out.write("	     \r\n");
      out.write("	 	      // 클릭한 날짜를 보여주는 div 업데이트\r\n");
      out.write("	 	      document.getElementById('selected-date').innerText =  info.dateStr;\r\n");
      out.write("	 	      \r\n");
      out.write("	 	      // 선택한 날짜 select-date 의 value값을 info.dateStr로 설정  \r\n");
      out.write("	 	      document.getElementById('select_date').value = info.dateStr;\r\n");
      out.write("	 	      \r\n");
      out.write("	 	      // 선택한 날짜에 대한 데이터 조회 \r\n");
      out.write("	 	      \r\n");
      out.write("	 	      $.ajax({\r\n");
      out.write("	 	          url: 'diary_select_date.do',\r\n");
      out.write("	 	          type: 'GET',\r\n");
      out.write("	 	          data: { date: info.dateStr },\r\n");
      out.write("	 	          success: function(response) {\r\n");
      out.write("	 	              // 컨트롤러에서 받아온 데이터를 html로 변환\r\n");
      out.write("	 	              let test = generate_html(response);\r\n");
      out.write("	 	              \r\n");
      out.write("	 	              // HTML을 페이지에 삽입\r\n");
      out.write("	 	              $('#diary_select_date').html(test);\r\n");
      out.write("	 	          },\r\n");
      out.write("	 	          error: function(error) {\r\n");
      out.write("	 	              console.error('Error fetching data:', error);\r\n");
      out.write("	 	          }\r\n");
      out.write("	 	      }); \r\n");
      out.write("	 	    \r\n");
      out.write("	     },\r\n");
      out.write("	     navLinks: true, // can click day/week names to navigate views\r\n");
      out.write("	     editable: true,\r\n");
      out.write("	     dayMaxEvents: true, // allow \"more\" link when too many events\r\n");
      out.write("	     /* googleCalendarApiKey: 'AIzaSyAUuo-Kz_4zD8A2oFrLmGPS9BKySc6BPVA',\r\n");
      out.write("	     eventSources: [{\r\n");
      out.write("	               googleCalendarId: 'ko.south_korea#holiday@group.v.calendar.google.com',\r\n");
      out.write("	               className: '공휴일',\r\n");
      out.write("	               color: 'yellow', //rgb,#ffffff 등의 형식으로 할 수 있어요.\r\n");
      out.write("	               //textColor: 'black' \r\n");
      out.write("	     }], */\r\n");
      out.write("	     events: [\r\n");
      out.write("	       {\r\n");
      out.write("	         title: 'All Day Event',\r\n");
      out.write("	         start: '2023-01-01'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         title: 'Long Event',\r\n");
      out.write("	         start: '2023-01-07',\r\n");
      out.write("	         end: '2023-01-10'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         groupId: 999,\r\n");
      out.write("	         title: 'Repeating Event',\r\n");
      out.write("	         start: '2023-01-09T16:00:00'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         groupId: 999,\r\n");
      out.write("	         title: 'Repeating Event',\r\n");
      out.write("	         start: '2023-01-16T16:00:00'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         title: 'Conference',\r\n");
      out.write("	         start: '2023-01-11',\r\n");
      out.write("	         end: '2023-01-13'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         title: 'Meeting',\r\n");
      out.write("	         start: '2023-01-12T10:30:00',\r\n");
      out.write("	         end: '2023-01-12T12:30:00'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         title: 'Lunch',\r\n");
      out.write("	         start: '2023-01-12T12:00:00'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         title: 'Meeting',\r\n");
      out.write("	         start: '2023-01-12T14:30:00'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         title: 'Happy Hour',\r\n");
      out.write("	         start: '2023-01-12T17:30:00'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         title: 'Dinner',\r\n");
      out.write("	         start: '2023-01-12T20:00:00'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         title: 'Birthday Party',\r\n");
      out.write("	         start: '2023-01-13T07:00:00'\r\n");
      out.write("	       },\r\n");
      out.write("	       {\r\n");
      out.write("	         title: 'Click for Google',\r\n");
      out.write("	         url: 'http://google.com/',\r\n");
      out.write("	         start: '2023-01-28'\r\n");
      out.write("	       }\r\n");
      out.write("	     ] \r\n");
      out.write("	   }); // calendar\r\n");
      out.write("\r\n");
      out.write("	   calendar.render();\r\n");
      out.write("	 }); // addEventListener\r\n");
      out.write("	 \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("	margin: 40px 10px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("#calendar {\r\n");
      out.write("	max-width: 1100px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	margin-top: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#memo-form-container {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("	width: 800px;\r\n");
      out.write("	height: 600px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .th_h{\r\n");
      out.write("	margin-top:15px !important;\r\n");
      out.write("} */\r\n");
      out.write(".container th {\r\n");
      out.write("	/* color:red !important; */\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	text-align:center;\r\n");
      out.write("	color:#3C4043 !important;\r\n");
      out.write("	padding:20px !important;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	margin:0px !important;\r\n");
      out.write("}\r\n");
      out.write(".container td {\r\n");
      out.write("	padding:20px !important;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container td, .container th{\r\n");
      out.write("	border:none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*  diary-btn-yellow  */\r\n");
      out.write(".diary-btn-yellow {\r\n");
      out.write("	background-color: #FADA5A;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding: 15px 30px;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	transition: 0.25s;\r\n");
      out.write("	letter-spacing: 2px;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".diary-btn-yellow:hover {\r\n");
      out.write("	transform: scale(1.1);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".diary-btn-yellow:active {\r\n");
      out.write("	transform: scale(0.9);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*  diary-btn-yellow-outline  */\r\n");
      out.write(".diary-btn-yellow-outline {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border: 3px solid #FADA5A;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding: 15px 30px;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	transition: 0.25s;\r\n");
      out.write("	letter-spacing: 2px;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".diary-btn-yellow-outline:hover {\r\n");
      out.write("	transform: scale(1.1);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".diary-btn-yellow-outline:active {\r\n");
      out.write("	transform: scale(0.9);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*  diary-btn-gray-outline  */\r\n");
      out.write(".diary-btn-gray-outline {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border: 3px solid #C0C0C0;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding: 15px 30px;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	transition: 0.25s;\r\n");
      out.write("	letter-spacing: 2px;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".diary-btn-gray-outline:hover {\r\n");
      out.write("	transform: scale(1.1);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".diary-btn-gray-outline:active {\r\n");
      out.write("	transform: scale(0.9);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#selected-date { \r\n");
      out.write("	font-size:27px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function diary_insert_form(){\r\n");
      out.write("		// 로그인 여부 체크\r\n");
      out.write("/* 		if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty user }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"true\"){\r\n");
      out.write("					\r\n");
      out.write("			if(confirm(\"글쓰기는 로그인 후 가능합니다.\\n로그인 하시겠습니까?\") == false) return;\r\n");
      out.write("			\r\n");
      out.write("			// 로그인 폼으로 이동 \r\n");
      out.write("			location.href = \"../member/login_form.do\";\r\n");
      out.write("			\r\n");
      out.write("			return;\r\n");
      out.write("		} */\r\n");
      out.write("		\r\n");
      out.write("		var select_date = document.getElementById('select_date').value;\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		// 선택한 날짜 들고 이동하기 \r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		// 새글쓰기 폼 띄우기 \r\n");
      out.write("		location.href=\"diary_insert_form.do?select_date=\"+select_date;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- top 옵션-->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<title>반려동물종합관리플랫폼</title>\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link href=\"../resources/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("<link href=\"../resources/assets/img/apple-touch-icon.png\"\r\n");
      out.write("	rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Fonts -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com\" rel=\"preconnect\">\r\n");
      out.write("<link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS Files -->\r\n");
      out.write("<link href=\"../resources/assets/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"../resources/assets/vendor/bootstrap-icons/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../resources/assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../resources/assets/vendor/glightbox/css/glightbox.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../resources/assets/vendor/swiper/swiper-bundle.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main CSS File -->\r\n");
      out.write("<link href=\"../resources/assets/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- =======================================================\r\n");
      out.write("  * Template Name: Impact\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/impact-bootstrap-business-website-template/\r\n");
      out.write("  * Updated: Jun 29 2024 with Bootstrap v5.3.3\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 공통 css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/common.css\">\r\n");
      out.write("\r\n");
      out.write("<!--  부트스트랩 스타일 수정  -->\r\n");
      out.write("<style>\r\n");
      out.write(".accent-background {\r\n");
      out.write("	background-color: white !important;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".accent-background p {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topbar {\r\n");
      out.write("	background-color: #FADA5A !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navmenu a {\r\n");
      out.write("	font-family: 'Noto Sans KR', sans-serif !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".branding, .branding a, .branding h1 {\r\n");
      out.write("	background-color: #F2EFE5 !important; /*  C7C8CC */\r\n");
      out.write("	color: #3C4043 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".branding a:hover, .branding a:focus, .branding a:active {\r\n");
      out.write("	color: #3C4043 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-box {\r\n");
      out.write("	background-color: #FADA5A !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("	background-color: gray !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@font-face {\r\n");
      out.write("	font-family: 'RixInooAriDuriR';\r\n");
      out.write("	src:\r\n");
      out.write("		url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_2207-01@1.0/RixInooAriDuriR.woff2')\r\n");
      out.write("		format('woff2');\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@font-face {\r\n");
      out.write("	font-family: 'Noto Sans KR';\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	src: url(//fonts.gstatic.com/ea/notosanskr/v2/NotoSansKR-Medium.woff2)\r\n");
      out.write("		format('woff2'),\r\n");
      out.write("		url(//fonts.gstatic.com/ea/notosanskr/v2/NotoSansKR-Medium.woff)\r\n");
      out.write("		format('woff'),\r\n");
      out.write("		url(//fonts.gstatic.com/ea/notosanskr/v2/NotoSansKR-Medium.otf)\r\n");
      out.write("		format('opentype');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body, header {\r\n");
      out.write("	/* font-family: 'RixInooAriDuriR'; */\r\n");
      out.write("	font-family: 'Noto Sans KR', sans-serif !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	font-family: 'Noto Sans KR', sans-serif !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-box {\r\n");
      out.write("	border-radius: 20px !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function login_check() {\r\n");
      out.write("\r\n");
      out.write("		location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login_form.do?url=\"\r\n");
      out.write("				+ encodeURIComponent(location.href);\r\n");
      out.write("		return;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body class=\"index-page\">\r\n");
      out.write("	<header id=\"header\" class=\"header fixed-top\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"topbar d-flex align-items-center\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"container d-flex justify-content-center justify-content-md-between\">\r\n");
      out.write("				<div class=\"contact-info d-flex align-items-center\">\r\n");
      out.write("					<i class=\"bi bi-envelope d-flex align-items-center\"><a\r\n");
      out.write("						href=\"mailto:contact@example.com\">contact@example.com</a></i> <i\r\n");
      out.write("						class=\"bi bi-phone d-flex align-items-center ms-4\"><span>+1\r\n");
      out.write("							5589 55488 55</span></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"social-links d-none d-md-flex align-items-center\">\r\n");
      out.write("					<!-- <div>\r\n");
      out.write("						<input type=\"button\" value=\"로그인\" onclick=\"login_check();\">\r\n");
      out.write("					</div> -->\r\n");
      out.write("\r\n");
      out.write("					<a href=\"#\" class=\"twitter\"><i class=\"bi bi-twitter-x\"></i></a> <a\r\n");
      out.write("						href=\"#\" class=\"facebook\"><i class=\"bi bi-facebook\"></i></a> <a\r\n");
      out.write("						href=\"#\" class=\"instagram\"><i class=\"bi bi-instagram\"></i></a> <a\r\n");
      out.write("						href=\"#\" class=\"linkedin\"><i class=\"bi bi-linkedin\"></i></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text-end\">\r\n");
      out.write("					<!-- 로그인이 안되어 있는 경우  -->\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					<!-- 로그인이 되어 있는 경우  -->\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Top Bar -->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"branding d-flex align-items-cente\">\r\n");
      out.write("\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"container position-relative d-flex align-items-center justify-content-between\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\"\r\n");
      out.write("					class=\"logo d-flex align-items-center\"> <!-- Uncomment the line below if you also wish to use an image logo -->\r\n");
      out.write("					<img\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo.png\"\r\n");
      out.write("					alt=\"\">\r\n");
      out.write("					<h1 class=\"sitename\"></h1>\r\n");
      out.write("				</a>\r\n");
      out.write("				<nav id=\"navmenu\" class=\"navmenu\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a\r\n");
      out.write("							href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/diary/diary_list.do\">다이어리<br></a></li>\r\n");
      out.write("						<li class=\"dropdown\"><a><span>커뮤니티</span> <i\r\n");
      out.write("								class=\"bi bi-chevron-down toggle-dropdown\"></i></a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list.do?b_cate=free\">자유게시판</a></li>\r\n");
      out.write("								<li><a\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list.do?b_cate=medical\">의학상담</a></li>\r\n");
      out.write("								<li><a\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list.do?b_cate=mate\">동네친구</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a\r\n");
      out.write("							href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/location/location.do\">플레이스</a></li>\r\n");
      out.write("						<li><a\r\n");
      out.write("							href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/news/news.do\">뉴스</a></li>\r\n");
      out.write("						<li><a href=\"#team\">쇼핑몰</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><a href=\"#\">문의</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<i class=\"mobile-nav-toggle d-xl-none bi bi-list\"></i>\r\n");
      out.write("				</nav>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div id='calendar'></div>\r\n");
      out.write("\r\n");
      out.write("	<div id='selected-date' style=\"text-align: center; margin-top: 20px;\"></div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"col-sm-4\">\r\n");
      out.write("		<form>\r\n");
      out.write("			<input type=hidden id=\"select_date\"> \r\n");
      out.write("			<input class=\"btn btn-info\" type=\"button\" value=\"추가하기\"\r\n");
      out.write("				onclick=\"diary_insert_form()\">\r\n");
      out.write("		</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id='diary_select_date'></div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!-- 산책 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 체중 -->\r\n");
      out.write("	    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 사료/간식/영양제 -->\r\n");
      out.write("	    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("	<input class=\"diary-btn-yellow\" type=\"button\" value=\"등록\"\r\n");
      out.write("		onclick=\"send(this.form);\"> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("	<input class=\"diary-btn-yellow-outline\" type=\"button\" value=\"등록\"\r\n");
      out.write("		onclick=\"\"> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("	<input class=\"diary-btn-gray-outline\" type=\"button\" value=\"등록\"\r\n");
      out.write("		onclick=\"\">\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/diary/../top.jsp(158,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sessionScope.user }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<input class=\"btn btn-default\" type=\"button\" value=\"로그인\"\r\n");
          out.write("							onclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/login_form.do'\">\r\n");
          out.write("						<input class=\"btn btn-default\" type=\"button\" value=\"회원가입\"\r\n");
          out.write("							onclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/insert_form.do'\">\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/diary/../top.jsp(165,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty sessionScope.user }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<input class=\"btn btn-default\" type=\"button\" value=\"로그아웃\"\r\n");
          out.write("							onclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout.do'\">\r\n");
          out.write("						<input class=\"btn btn-default\" type=\"button\" value=\"마이페이지\">\r\n");
          out.write("						<!-- 로그인이 되어 있고 관리자인 경우  -->\r\n");
          out.write("						");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/diary/../top.jsp(170,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.user.m_grade == '관리자'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<input class=\"btn btn-info\" type=\"button\" value=\"관리자페이지\">\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/diary/diary_list.jsp(569,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("vo");
      // /WEB-INF/views/diary/diary_list.jsp(569,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/diary/diary_list.jsp(569,5) '${ weight_list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ weight_list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			<form action=\"diary_modify_form.do\" method=\"post\">\r\n");
            out.write("				<table class=\"table\">\r\n");
            out.write("					<tbody><tr>\r\n");
            out.write("						<th>날짜</th>\r\n");
            out.write("						<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"w_rdate\" value=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ vo.w_rdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("></td>\r\n");
            out.write("					</tr>\r\n");
            out.write("					<tr>\r\n");
            out.write("						<th>반려동물</th>\r\n");
            out.write("						<td><input class=\"form-control form-control-lg\" type=\"text\" name=\"p_idx\" value=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ vo.p_idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("></td>\r\n");
            out.write("					</tr>\r\n");
            out.write("					<tr>\r\n");
            out.write("						<th>체중(kg)</th>\r\n");
            out.write("						<td><input class=\"form-control form-control-lg\" type=\"number\" name=\"w_weight\" value=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ vo.w_weight }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("></td>\r\n");
            out.write("					</tr>\r\n");
            out.write("				</tbody></table>\r\n");
            out.write("\r\n");
            out.write("				<div class=\"container\" style=\"text-align: center;\">\r\n");
            out.write("					<input class=\"diary-btn-yellow\" type=\"button\" value=\"수정\" onclick=\"send(this.form);\">\r\n");
            out.write("				</div>\r\n");
            out.write("\r\n");
            out.write("			</form>\r\n");
            out.write("		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
